import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const STADIUMS = [
  'MetLife Stadium (New York/New Jersey)',  //0
  'SoFi Stadium (Los Angeles)',             //1
  'Estadio Azteca (Mexico City)',           //2
  'AT&T Stadium (Dallas)',                  //3
  'Hard Rock Stadium (Miami)',              //4
  'Mercedes-Benz Stadium (Atlanta)',        //5
  'Lumen Field (Seattle)',                  //6
  'BC Place (Vancouver)',                   //7
  'BMO Field (Toronto)',                    //8
  'Estadio BBVA (Monterrey)',               //9
  'Estadio Akron (Guadalajara)',            //10
  'Lincoln Financial Field (Philadelphia)',//11
  'Levi\'s Stadium (San Francisco)',       //12
  'Gillette Stadium (Boston)',              //13
  'NRG Stadium (Houston)',                  //14
  'Arrowhead Stadium (Kansas City)'          //15
];

const GROUPS = [
  {
    name: 'Grupo A',
    teams: [
      { name: 'México', abbrev: 'MEX', flag: '🇲🇽' },
      { name: 'África do Sul', abbrev: 'RSA', flag: '🇿🇦' },
      { name: 'Coreia do Sul', abbrev: 'KOR', flag: '🇰🇷' },
      { name: 'Tchéquia', abbrev: 'CZE', flag: '🇨🇿' }
    ]
  },
  {
    name: 'Grupo B',
    teams: [
      { name: 'Canadá', abbrev: 'CAN', flag: '🇨🇦' },
      { name: 'Bósnia e Herzegovina', abbrev: 'BIH', flag: '🇧🇦' },
      { name: 'Catar', abbrev: 'QAT', flag: '🇶🇦' },
      { name: 'Suíça', abbrev: 'SUI', flag: '🇨🇭' }
    ]
  },
  {
    name: 'Grupo C',
    teams: [
      { name: 'Brasil', abbrev: 'BRA', flag: '🇧🇷' },
      { name: 'Marrocos', abbrev: 'MAR', flag: '🇲🇦' },
      { name: 'Haiti', abbrev: 'HTI', flag: '🇭🇹' },
      { name: 'Escócia', abbrev: 'SCO', flag: '🏴' }
    ]
  },
  {
    name: 'Grupo D',
    teams: [
      { name: 'Estados Unidos', abbrev: 'USA', flag: '🇺🇸' },
      { name: 'Paraguai', abbrev: 'PAR', flag: '🇵🇾' },
      { name: 'Austrália', abbrev: 'AUS', flag: '🇦🇺' },
      { name: 'Turquia', abbrev: 'TUR', flag: '🇹🇷' }
    ]
  },
  {
    name: 'Grupo E',
    teams: [
      { name: 'Alemanha', abbrev: 'GER', flag: '🇩🇪' },
      { name: 'Curaçao', abbrev: 'CUW', flag: '🇨🇼' },
      { name: 'Costa do Marfim', abbrev: 'CIV', flag: '🇨🇮' },
      { name: 'Equador', abbrev: 'ECU', flag: '🇪🇨' }
    ]
  },
  {
    name: 'Grupo F',
    teams: [
      { name: 'Holanda', abbrev: 'NED', flag: '🇳🇱' },
      { name: 'Japão', abbrev: 'JPN', flag: '🇯🇵' },
      { name: 'Suécia', abbrev: 'SWE', flag: '🇸🇪' },
      { name: 'Tunísia', abbrev: 'TUN', flag: '🇹🇳' }
    ]
  },
  {
    name: 'Grupo G',
    teams: [
      { name: 'Bélgica', abbrev: 'BEL', flag: '🇧🇪' },
      { name: 'Egito', abbrev: 'EGY', flag: '🇪🇬' },
      { name: 'Irã', abbrev: 'IRN', flag: '🇮🇷' },
      { name: 'Nova Zelândia', abbrev: 'NZL', flag: '🇳🇿' }
    ]
  },
  {
    name: 'Grupo H',
    teams: [
      { name: 'Espanha', abbrev: 'ESP', flag: '🇪🇸' },
      { name: 'Cabo Verde', abbrev: 'CPV', flag: '🇨🇻' },
      { name: 'Arábia Saudita', abbrev: 'KSA', flag: '🇸🇦' },
      { name: 'Uruguai', abbrev: 'URU', flag: '🇺🇾' }
    ]
  },
  {
    name: 'Grupo I',
    teams: [
      { name: 'França', abbrev: 'FRA', flag: '🇫🇷' },
      { name: 'Senegal', abbrev: 'SEN', flag: '🇸🇳' },
      { name: 'Iraque', abbrev: 'IRQ', flag: '🇮🇶' },
      { name: 'Noruega', abbrev: 'NOR', flag: '🇳🇴' }
    ]
  },
  {
    name: 'Grupo J',
    teams: [
      { name: 'Argentina', abbrev: 'ARG', flag: '🇦🇷' },
      { name: 'Argélia', abbrev: 'ALG', flag: '🇩🇿' },
      { name: 'Áustria', abbrev: 'AUT', flag: '🇦🇹' },
      { name: 'Jordânia', abbrev: 'JOR', flag: '🇯🇴' }
    ]
  },
  {
    name: 'Grupo K',
    teams: [
      { name: 'Portugal', abbrev: 'POR', flag: '🇵🇹' },
      { name: 'República Democrática do Congo', abbrev: 'COD', flag: '🇨🇩' },
      { name: 'Uzbequistão', abbrev: 'UZB', flag: '🇺🇿' },
      { name: 'Colômbia', abbrev: 'COL', flag: '🇨🇴' }
    ]
  },
  {
    name: 'Grupo L',
    teams: [
      { name: 'Inglaterra', abbrev: 'ENG', flag: '🏴' },
      { name: 'Croácia', abbrev: 'CRO', flag: '🇭🇷' },
      { name: 'Gana', abbrev: 'GHA', flag: '🇬🇭' },
      { name: 'Panamá', abbrev: 'PAN', flag: '🇵🇦' }
    ]
  }
];

async function main() {
  console.log('Limpando banco de dados...');
  await prisma.prediction.deleteMany();
  await prisma.game.deleteMany();
  await prisma.player.deleteMany();

  console.log('Semeando jogos da fase de grupos...');
  let gameCount = 0;

  // Start group matches on June 11, 2026.
  let baseDate = new Date('2026-06-11T16:00:00Z');

  const allMatches = [
    {
      "id": 1,
      "stage": "Grupo A",
      "stadium": "Estadio Azteca - Cidade do México, México",
      "date": "2026-06-11T16:00:00-03:00",
      "teamA": "Mexico",
      "flagA": "🇲🇽",
      "abbrevA": "MEX",
      "teamB": "South Africa",
      "flagB": "🇿🇦",
      "abbrevB": "RSA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 2,
      "stage": "Grupo A",
      "stadium": "Estadio Akron - Guadalajara, México",
      "date": "2026-06-11T23:00:00-03:00",
      "teamA": "Korea Republic",
      "flagA": "🇰🇷",
      "abbrevA": "KOR",
      "teamB": "Czechia",
      "flagB": "🇨🇿",
      "abbrevB": "CZE",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 3,
      "stage": "Grupo B",
      "stadium": "BMO Field - Toronto, Canadá",
      "date": "2026-06-12T16:00:00-03:00",
      "teamA": "Canada",
      "flagA": "🇨🇦",
      "abbrevA": "CAN",
      "teamB": "Bosnia and Herzegovina",
      "flagB": "🇧🇦",
      "abbrevB": "BIH",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 4,
      "stage": "Grupo D",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-06-12T22:00:00-03:00",
      "teamA": "USA",
      "flagA": "🇺🇸",
      "abbrevA": "USA",
      "teamB": "Paraguay",
      "flagB": "🇵🇾",
      "abbrevB": "PAR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 5,
      "stage": "Grupo B",
      "stadium": "Levi’s Stadium - San Francisco Bay Area, EUA",
      "date": "2026-06-13T16:00:00-03:00",
      "teamA": "Qatar",
      "flagA": "🇶🇦",
      "abbrevA": "QAT",
      "teamB": "Switzerland",
      "flagB": "🇨🇭",
      "abbrevB": "SUI",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 6,
      "stage": "Grupo C",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-06-13T19:00:00-03:00",
      "teamA": "Brazil",
      "flagA": "🇧🇷",
      "abbrevA": "BRA",
      "teamB": "Morocco",
      "flagB": "🇲🇦",
      "abbrevB": "MAR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 7,
      "stage": "Grupo C",
      "stadium": "Gillette Stadium - Boston, EUA",
      "date": "2026-06-13T22:00:00-03:00",
      "teamA": "Haiti",
      "flagA": "🇭🇹",
      "abbrevA": "HTI",
      "teamB": "Scotland",
      "flagB": "🏴",
      "abbrevB": "SCO",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 8,
      "stage": "Grupo D",
      "stadium": "BC Place - Vancouver, Canadá",
      "date": "2026-06-14T01:00:00-03:00",
      "teamA": "Australia",
      "flagA": "🇦🇺",
      "abbrevA": "AUS",
      "teamB": "Türkiye",
      "flagB": "🇹🇷",
      "abbrevB": "TUR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 9,
      "stage": "Grupo E",
      "stadium": "NRG Stadium - Houston, EUA",
      "date": "2026-06-14T14:00:00-03:00",
      "teamA": "Germany",
      "flagA": "🇩🇪",
      "abbrevA": "GER",
      "teamB": "Curaçao",
      "flagB": "🇨🇼",
      "abbrevB": "CUW",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 10,
      "stage": "Grupo F",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-06-14T17:00:00-03:00",
      "teamA": "Netherlands",
      "flagA": "🇳🇱",
      "abbrevA": "NED",
      "teamB": "Japan",
      "flagB": "🇯🇵",
      "abbrevB": "JPN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 11,
      "stage": "Grupo E",
      "stadium": "Lincoln Financial Field - Philadelphia, EUA",
      "date": "2026-06-14T20:00:00-03:00",
      "teamA": "Côte d'Ivoire",
      "flagA": "🇨🇮",
      "abbrevA": "CIV",
      "teamB": "Ecuador",
      "flagB": "🇪🇨",
      "abbrevB": "ECU",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 12,
      "stage": "Grupo F",
      "stadium": "Estadio BBVA - Monterrey, México",
      "date": "2026-06-14T23:00:00-03:00",
      "teamA": "Sweden",
      "flagA": "🇸🇪",
      "abbrevA": "SWE",
      "teamB": "Tunisia",
      "flagB": "🇹🇳",
      "abbrevB": "TUN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 13,
      "stage": "Grupo H",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-06-15T13:00:00-03:00",
      "teamA": "Spain",
      "flagA": "🇪🇸",
      "abbrevA": "ESP",
      "teamB": "Cabo Verde",
      "flagB": "🇨🇻",
      "abbrevB": "CPV",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 14,
      "stage": "Grupo G",
      "stadium": "Lumen Field - Seattle, EUA",
      "date": "2026-06-15T16:00:00-03:00",
      "teamA": "Belgium",
      "flagA": "🇧🇪",
      "abbrevA": "BEL",
      "teamB": "Egypt",
      "flagB": "🇪🇬",
      "abbrevB": "EGY",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 15,
      "stage": "Grupo H",
      "stadium": "Hard Rock Stadium - Miami, EUA",
      "date": "2026-06-15T19:00:00-03:00",
      "teamA": "Saudi Arabia",
      "flagA": "🇸🇦",
      "abbrevA": "KSA",
      "teamB": "Uruguay",
      "flagB": "🇺🇾",
      "abbrevB": "URU",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 16,
      "stage": "Grupo G",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-06-15T22:00:00-03:00",
      "teamA": "IR Iran",
      "flagA": "🇮🇷",
      "abbrevA": "IRN",
      "teamB": "New Zealand",
      "flagB": "🇳🇿",
      "abbrevB": "NZL",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 17,
      "stage": "Grupo I",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-06-16T16:00:00-03:00",
      "teamA": "France",
      "flagA": "🇫🇷",
      "abbrevA": "FRA",
      "teamB": "Senegal",
      "flagB": "🇸🇳",
      "abbrevB": "SEN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 18,
      "stage": "Grupo I",
      "stadium": "Gillette Stadium - Boston, EUA",
      "date": "2026-06-16T19:00:00-03:00",
      "teamA": "Iraq",
      "flagA": "🇮🇶",
      "abbrevA": "IRQ",
      "teamB": "Norway",
      "flagB": "🇳🇴",
      "abbrevB": "NOR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 19,
      "stage": "Grupo J",
      "stadium": "Arrowhead Stadium - Kansas City, EUA",
      "date": "2026-06-16T22:00:00-03:00",
      "teamA": "Argentina",
      "flagA": "🇦🇷",
      "abbrevA": "ARG",
      "teamB": "Algeria",
      "flagB": "🇩🇿",
      "abbrevB": "ALG",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 20,
      "stage": "Grupo J",
      "stadium": "Levi’s Stadium - San Francisco Bay Area, EUA",
      "date": "2026-06-17T01:00:00-03:00",
      "teamA": "Austria",
      "flagA": "🇦🇹",
      "abbrevA": "AUT",
      "teamB": "Jordan",
      "flagB": "🇯🇴",
      "abbrevB": "JOR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 21,
      "stage": "Grupo K",
      "stadium": "NRG Stadium - Houston, EUA",
      "date": "2026-06-17T14:00:00-03:00",
      "teamA": "Portugal",
      "flagA": "🇵🇹",
      "abbrevA": "POR",
      "teamB": "Democratic Republic of Congo",
      "flagB": "🇨🇩",
      "abbrevB": "COD",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 22,
      "stage": "Grupo L",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-06-17T17:00:00-03:00",
      "teamA": "England",
      "flagA": "🏴",
      "abbrevA": "ENG",
      "teamB": "Croatia",
      "flagB": "🇭🇷",
      "abbrevB": "CRO",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 23,
      "stage": "Grupo L",
      "stadium": "BMO Field - Toronto, Canadá",
      "date": "2026-06-17T20:00:00-03:00",
      "teamA": "Ghana",
      "flagA": "🇬🇭",
      "abbrevA": "GHA",
      "teamB": "Panama",
      "flagB": "🇵🇦",
      "abbrevB": "PAN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 24,
      "stage": "Grupo K",
      "stadium": "Estadio Azteca - Cidade do México, México",
      "date": "2026-06-17T23:00:00-03:00",
      "teamA": "Uzbekistan",
      "flagA": "🇺🇿",
      "abbrevA": "UZB",
      "teamB": "Colombia",
      "flagB": "🇨🇴",
      "abbrevB": "COL",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 25,
      "stage": "Grupo A",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-06-18T13:00:00-03:00",
      "teamA": "Czechia",
      "flagA": "🇨🇿",
      "abbrevA": "CZE",
      "teamB": "South Africa",
      "flagB": "🇿🇦",
      "abbrevB": "RSA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 26,
      "stage": "Grupo B",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-06-18T16:00:00-03:00",
      "teamA": "Switzerland",
      "flagA": "🇨🇭",
      "abbrevA": "SUI",
      "teamB": "Bosnia and Herzegovina",
      "flagB": "🇧🇦",
      "abbrevB": "BIH",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 27,
      "stage": "Grupo B",
      "stadium": "BC Place - Vancouver, Canadá",
      "date": "2026-06-18T19:00:00-03:00",
      "teamA": "Canada",
      "flagA": "🇨🇦",
      "abbrevA": "CAN",
      "teamB": "Qatar",
      "flagB": "🇶🇦",
      "abbrevB": "QAT",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 28,
      "stage": "Grupo A",
      "stadium": "Estadio Akron - Guadalajara, México",
      "date": "2026-06-18T22:00:00-03:00",
      "teamA": "Mexico",
      "flagA": "🇲🇽",
      "abbrevA": "MEX",
      "teamB": "Korea Republic",
      "flagB": "🇰🇷",
      "abbrevB": "KOR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 29,
      "stage": "Grupo C",
      "stadium": "Gillette Stadium - Boston, EUA",
      "date": "2026-06-19T19:00:00-03:00",
      "teamA": "Scotland",
      "flagA": "🏴",
      "abbrevA": "SCO",
      "teamB": "Morocco",
      "flagB": "🇲🇦",
      "abbrevB": "MAR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 30,
      "stage": "Grupo D",
      "stadium": "Levi’s Stadium - San Francisco Bay Area, EUA",
      "date": "2026-06-19T21:00:00-03:00",
      "teamA": "Türkiye",
      "flagA": "🇹🇷",
      "abbrevA": "TUR",
      "teamB": "Paraguay",
      "flagB": "🇵🇾",
      "abbrevB": "PAR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 31,
      "stage": "Grupo C",
      "stadium": "Lincoln Financial Field - Philadelphia, EUA",
      "date": "2026-06-19T22:00:00-03:00",
      "teamA": "Brazil",
      "flagA": "🇧🇷",
      "abbrevA": "BRA",
      "teamB": "Haiti",
      "flagB": "🇭🇹",
      "abbrevB": "HTI",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 32,
      "stage": "Grupo D",
      "stadium": "Lumen Field - Seattle, EUA",
      "date": "2026-06-19T16:00:00-03:00",
      "teamA": "USA",
      "flagA": "🇺🇸",
      "abbrevA": "USA",
      "teamB": "Australia",
      "flagB": "🇦🇺",
      "abbrevB": "AUS",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 33,
      "stage": "Grupo E",
      "stadium": "BMO Field - Toronto, Canadá",
      "date": "2026-06-20T17:00:00-03:00",
      "teamA": "Germany",
      "flagA": "🇩🇪",
      "abbrevA": "GER",
      "teamB": "Côte d'Ivoire",
      "flagB": "🇨🇮",
      "abbrevB": "CIV",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 34,
      "stage": "Grupo E",
      "stadium": "Arrowhead Stadium - Kansas City, EUA",
      "date": "2026-06-20T21:00:00-03:00",
      "teamA": "Ecuador",
      "flagA": "🇪🇨",
      "abbrevA": "ECU",
      "teamB": "Curaçao",
      "flagB": "🇨🇼",
      "abbrevB": "CUW",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 35,
      "stage": "Grupo F",
      "stadium": "NRG Stadium - Houston, EUA",
      "date": "2026-06-20T14:00:00-03:00",
      "teamA": "Netherlands",
      "flagA": "🇳🇱",
      "abbrevA": "NED",
      "teamB": "Sweden",
      "flagB": "🇸🇪",
      "abbrevB": "SWE",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 36,
      "stage": "Grupo F",
      "stadium": "Estadio BBVA - Monterrey, México",
      "date": "2026-06-21T01:00:00-03:00",
      "teamA": "Tunisia",
      "flagA": "🇹🇳",
      "abbrevA": "TUN",
      "teamB": "Japan",
      "flagB": "🇯🇵",
      "abbrevB": "JPN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 37,
      "stage": "Grupo G",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-06-21T16:00:00-03:00",
      "teamA": "Belgium",
      "flagA": "🇧🇪",
      "abbrevA": "BEL",
      "teamB": "IR Iran",
      "flagB": "🇮🇷",
      "abbrevB": "IRN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 38,
      "stage": "Grupo G",
      "stadium": "BC Place - Vancouver, Canadá",
      "date": "2026-06-21T22:00:00-03:00",
      "teamA": "New Zealand",
      "flagA": "🇳🇿",
      "abbrevA": "NZL",
      "teamB": "Egypt",
      "flagB": "🇪🇬",
      "abbrevB": "EGY",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 39,
      "stage": "Grupo H",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-06-21T13:00:00-03:00",
      "teamA": "Spain",
      "flagA": "🇪🇸",
      "abbrevA": "ESP",
      "teamB": "Saudi Arabia",
      "flagB": "🇸🇦",
      "abbrevB": "KSA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 40,
      "stage": "Grupo H",
      "stadium": "Hard Rock Stadium - Miami, EUA",
      "date": "2026-06-21T19:00:00-03:00",
      "teamA": "Uruguay",
      "flagA": "🇺🇾",
      "abbrevA": "URU",
      "teamB": "Cabo Verde",
      "flagB": "🇨🇻",
      "abbrevB": "CPV",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 41,
      "stage": "Grupo I",
      "stadium": "Lincoln Financial Field - Philadelphia, EUA",
      "date": "2026-06-22T18:00:00-03:00",
      "teamA": "France",
      "flagA": "🇫🇷",
      "abbrevA": "FRA",
      "teamB": "Iraq",
      "flagB": "🇮🇶",
      "abbrevB": "IRQ",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 42,
      "stage": "Grupo I",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-06-22T21:00:00-03:00",
      "teamA": "Norway",
      "flagA": "🇳🇴",
      "abbrevA": "NOR",
      "teamB": "Senegal",
      "flagB": "🇸🇳",
      "abbrevB": "SEN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 43,
      "stage": "Grupo J",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-06-22T14:00:00-03:00",
      "teamA": "Argentina",
      "flagA": "🇦🇷",
      "abbrevA": "ARG",
      "teamB": "Austria",
      "flagB": "🇦🇹",
      "abbrevB": "AUT",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 44,
      "stage": "Grupo J",
      "stadium": "Levi’s Stadium - San Francisco Bay Area, EUA",
      "date": "2026-06-23T00:00:00-03:00",
      "teamA": "Jordan",
      "flagA": "🇯🇴",
      "abbrevA": "JOR",
      "teamB": "Algeria",
      "flagB": "🇩🇿",
      "abbrevB": "ALG",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 45,
      "stage": "Grupo K",
      "stadium": "NRG Stadium - Houston, EUA",
      "date": "2026-06-23T14:00:00-03:00",
      "teamA": "Portugal",
      "flagA": "🇵🇹",
      "abbrevA": "POR",
      "teamB": "Uzbekistan",
      "flagB": "🇺🇿",
      "abbrevB": "UZB",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 46,
      "stage": "Grupo L",
      "stadium": "Gillette Stadium - Boston, EUA",
      "date": "2026-06-23T17:00:00-03:00",
      "teamA": "England",
      "flagA": "🏴",
      "abbrevA": "ENG",
      "teamB": "Ghana",
      "flagB": "🇬🇭",
      "abbrevB": "GHA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 47,
      "stage": "Grupo L",
      "stadium": "BMO Field - Toronto, Canadá",
      "date": "2026-06-23T20:00:00-03:00",
      "teamA": "Panama",
      "flagA": "🇵🇦",
      "abbrevA": "PAN",
      "teamB": "Croatia",
      "flagB": "🇭🇷",
      "abbrevB": "CRO",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 48,
      "stage": "Grupo K",
      "stadium": "Estadio Akron - Guadalajara, México",
      "date": "2026-06-23T23:00:00-03:00",
      "teamA": "Colombia",
      "flagA": "🇨🇴",
      "abbrevA": "COL",
      "teamB": "Democratic Republic of Congo",
      "flagB": "🇨🇩",
      "abbrevB": "COD",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 49,
      "stage": "Grupo B",
      "stadium": "BC Place - Vancouver, Canadá",
      "date": "2026-06-24T16:00:00-03:00",
      "teamA": "Switzerland",
      "flagA": "🇨🇭",
      "abbrevA": "SUI",
      "teamB": "Canada",
      "flagB": "🇨🇦",
      "abbrevB": "CAN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 50,
      "stage": "Grupo B",
      "stadium": "Lumen Field - Seattle, EUA",
      "date": "2026-06-24T16:00:00-03:00",
      "teamA": "Bosnia and Herzegovina",
      "flagA": "🇧🇦",
      "abbrevA": "BIH",
      "teamB": "Qatar",
      "flagB": "🇶🇦",
      "abbrevB": "QAT",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 51,
      "stage": "Grupo C",
      "stadium": "Hard Rock Stadium - Miami, EUA",
      "date": "2026-06-24T19:00:00-03:00",
      "teamA": "Scotland",
      "flagA": "🏴",
      "abbrevA": "SCO",
      "teamB": "Brazil",
      "flagB": "🇧🇷",
      "abbrevB": "BRA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 52,
      "stage": "Grupo C",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-06-24T19:00:00-03:00",
      "teamA": "Morocco",
      "flagA": "🇲🇦",
      "abbrevA": "MAR",
      "teamB": "Haiti",
      "flagB": "🇭🇹",
      "abbrevB": "HTI",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 53,
      "stage": "Grupo A",
      "stadium": "Estadio Azteca - Cidade do México, México",
      "date": "2026-06-24T22:00:00-03:00",
      "teamA": "Czechia",
      "flagA": "🇨🇿",
      "abbrevA": "CZE",
      "teamB": "Mexico",
      "flagB": "🇲🇽",
      "abbrevB": "MEX",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 54,
      "stage": "Grupo A",
      "stadium": "Estadio BBVA - Monterrey, México",
      "date": "2026-06-24T22:00:00-03:00",
      "teamA": "South Africa",
      "flagA": "🇿🇦",
      "abbrevA": "RSA",
      "teamB": "Korea Republic",
      "flagB": "🇰🇷",
      "abbrevB": "KOR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 55,
      "stage": "Grupo E",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-06-25T17:00:00-03:00",
      "teamA": "Ecuador",
      "flagA": "🇪🇨",
      "abbrevA": "ECU",
      "teamB": "Germany",
      "flagB": "🇩🇪",
      "abbrevB": "GER",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 56,
      "stage": "Grupo E",
      "stadium": "Lincoln Financial Field - Philadelphia, EUA",
      "date": "2026-06-25T17:00:00-03:00",
      "teamA": "Curaçao",
      "flagA": "🇨🇼",
      "abbrevA": "CUW",
      "teamB": "Côte d'Ivoire",
      "flagB": "🇨🇮",
      "abbrevB": "CIV",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 57,
      "stage": "Grupo F",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-06-25T20:00:00-03:00",
      "teamA": "Japan",
      "flagA": "🇯🇵",
      "abbrevA": "JPN",
      "teamB": "Sweden",
      "flagB": "🇸🇪",
      "abbrevB": "SWE",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 58,
      "stage": "Grupo F",
      "stadium": "Arrowhead Stadium - Kansas City, EUA",
      "date": "2026-06-25T20:00:00-03:00",
      "teamA": "Tunisia",
      "flagA": "🇹🇳",
      "abbrevA": "TUN",
      "teamB": "Netherlands",
      "flagB": "🇳🇱",
      "abbrevB": "NED",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 59,
      "stage": "Grupo D",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-06-25T23:00:00-03:00",
      "teamA": "Türkiye",
      "flagA": "🇹🇷",
      "abbrevA": "TUR",
      "teamB": "USA",
      "flagB": "🇺🇸",
      "abbrevB": "USA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 60,
      "stage": "Grupo D",
      "stadium": "Levi’s Stadium - San Francisco Bay Area, EUA",
      "date": "2026-06-25T23:00:00-03:00",
      "teamA": "Paraguay",
      "flagA": "🇵🇾",
      "abbrevA": "PAR",
      "teamB": "Australia",
      "flagB": "🇦🇺",
      "abbrevB": "AUS",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 61,
      "stage": "Grupo I",
      "stadium": "Gillette Stadium - Boston, EUA",
      "date": "2026-06-26T16:00:00-03:00",
      "teamA": "Norway",
      "flagA": "🇳🇴",
      "abbrevA": "NOR",
      "teamB": "France",
      "flagB": "🇫🇷",
      "abbrevB": "FRA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 62,
      "stage": "Grupo I",
      "stadium": "BMO Field - Toronto, Canadá",
      "date": "2026-06-26T16:00:00-03:00",
      "teamA": "Senegal",
      "flagA": "🇸🇳",
      "abbrevA": "SEN",
      "teamB": "Iraq",
      "flagB": "🇮🇶",
      "abbrevB": "IRQ",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 63,
      "stage": "Grupo H",
      "stadium": "NRG Stadium - Houston, EUA",
      "date": "2026-06-26T21:00:00-03:00",
      "teamA": "Cabo Verde",
      "flagA": "🇨🇻",
      "abbrevA": "CPV",
      "teamB": "Saudi Arabia",
      "flagB": "🇸🇦",
      "abbrevB": "KSA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 64,
      "stage": "Grupo H",
      "stadium": "Estadio Akron - Guadalajara, México",
      "date": "2026-06-26T21:00:00-03:00",
      "teamA": "Uruguay",
      "flagA": "🇺🇾",
      "abbrevA": "URU",
      "teamB": "Spain",
      "flagB": "🇪🇸",
      "abbrevB": "ESP",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 65,
      "stage": "Grupo G",
      "stadium": "Lumen Field - Seattle, EUA",
      "date": "2026-06-27T00:00:00-03:00",
      "teamA": "Egypt",
      "flagA": "🇪🇬",
      "abbrevA": "EGY",
      "teamB": "IR Iran",
      "flagB": "🇮🇷",
      "abbrevB": "IRN",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 66,
      "stage": "Grupo G",
      "stadium": "BC Place - Vancouver, Canadá",
      "date": "2026-06-27T00:00:00-03:00",
      "teamA": "New Zealand",
      "flagA": "🇳🇿",
      "abbrevA": "NZL",
      "teamB": "Belgium",
      "flagB": "🇧🇪",
      "abbrevB": "BEL",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 67,
      "stage": "Grupo L",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-06-27T18:00:00-03:00",
      "teamA": "Panama",
      "flagA": "🇵🇦",
      "abbrevA": "PAN",
      "teamB": "England",
      "flagB": "🏴",
      "abbrevB": "ENG",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 68,
      "stage": "Grupo L",
      "stadium": "Lincoln Financial Field - Philadelphia, EUA",
      "date": "2026-06-27T18:00:00-03:00",
      "teamA": "Croatia",
      "flagA": "🇭🇷",
      "abbrevA": "CRO",
      "teamB": "Ghana",
      "flagB": "🇬🇭",
      "abbrevB": "GHA",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 69,
      "stage": "Grupo J",
      "stadium": "Arrowhead Stadium - Kansas City, EUA",
      "date": "2026-06-27T23:00:00-03:00",
      "teamA": "Algeria",
      "flagA": "🇩🇿",
      "abbrevA": "ALG",
      "teamB": "Austria",
      "flagB": "🇦🇹",
      "abbrevB": "AUT",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 70,
      "stage": "Grupo J",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-06-27T23:00:00-03:00",
      "teamA": "Jordan",
      "flagA": "🇯🇴",
      "abbrevA": "JOR",
      "teamB": "Argentina",
      "flagB": "🇦🇷",
      "abbrevB": "ARG",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 71,
      "stage": "Grupo K",
      "stadium": "Hard Rock Stadium - Miami, EUA",
      "date": "2026-06-27T20:30:00-03:00",
      "teamA": "Colombia",
      "flagA": "🇨🇴",
      "abbrevA": "COL",
      "teamB": "Portugal",
      "flagB": "🇵🇹",
      "abbrevB": "POR",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 72,
      "stage": "Grupo K",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-06-27T20:30:00-03:00",
      "teamA": "Democratic Republic of Congo",
      "flagA": "🇨🇩",
      "abbrevA": "COD",
      "teamB": "Uzbekistan",
      "flagB": "🇺🇿",
      "abbrevB": "UZB",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 73,
      "stage": "16 avos de final",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-06-28T16:00:00-03:00",
      "teamA": "2º Grupo A",
      "flagA": "?",
      "abbrevA": "2A",
      "teamB": "2º Grupo B",
      "flagB": "?",
      "abbrevB": "2B",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 74,
      "stage": "16 avos de final",
      "stadium": "Gillette Stadium - Boston, EUA",
      "date": "2026-06-29T17:30:00-03:00",
      "teamA": "1º Grupo E",
      "flagA": "?",
      "abbrevA": "1E",
      "teamB": "3º colocado grupos A/B/C/D/F",
      "flagB": "?",
      "abbrevB": "3ABCDF",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 75,
      "stage": "16 avos de final",
      "stadium": "Estadio BBVA - Monterrey, México",
      "date": "2026-06-29T22:00:00-03:00",
      "teamA": "1º Grupo F",
      "flagA": "?",
      "abbrevA": "1F",
      "teamB": "2º Grupo C",
      "flagB": "?",
      "abbrevB": "2C",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 76,
      "stage": "16 avos de final",
      "stadium": "NRG Stadium - Houston, EUA",
      "date": "2026-06-29T14:00:00-03:00",
      "teamA": "1º Grupo C",
      "flagA": "?",
      "abbrevA": "1C",
      "teamB": "2º Grupo F",
      "flagB": "?",
      "abbrevB": "2F",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 77,
      "stage": "16 avos de final",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-06-30T18:00:00-03:00",
      "teamA": "1º Grupo I",
      "flagA": "?",
      "abbrevA": "1I",
      "teamB": "3º colocado grupos C/D/F/G/H",
      "flagB": "?",
      "abbrevB": "3CDFGH",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 78,
      "stage": "16 avos de final",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-06-30T14:00:00-03:00",
      "teamA": "2º Grupo E",
      "flagA": "?",
      "abbrevA": "2E",
      "teamB": "2º Grupo I",
      "flagB": "?",
      "abbrevB": "2I",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 79,
      "stage": "16 avos de final",
      "stadium": "Estadio Azteca - Cidade do México, México",
      "date": "2026-06-30T22:00:00-03:00",
      "teamA": "1º Grupo A",
      "flagA": "?",
      "abbrevA": "1A",
      "teamB": "3º colocado grupos C/E/F/H/I",
      "flagB": "?",
      "abbrevB": "3CEFHI",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 80,
      "stage": "16 avos de final",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-07-01T13:00:00-03:00",
      "teamA": "1º Grupo L",
      "flagA": "?",
      "abbrevA": "1L",
      "teamB": "3º colocado grupos E/H/I/J/K",
      "flagB": "?",
      "abbrevB": "3EHIJK",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 81,
      "stage": "16 avos de final",
      "stadium": "Levi’s Stadium - San Francisco Bay Area, EUA",
      "date": "2026-07-01T21:00:00-03:00",
      "teamA": "1º Grupo D",
      "flagA": "?",
      "abbrevA": "1D",
      "teamB": "3º colocado grupos B/E/F/I/J",
      "flagB": "?",
      "abbrevB": "3BEFIJ",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 82,
      "stage": "16 avos de final",
      "stadium": "Lumen Field - Seattle, EUA",
      "date": "2026-07-01T17:00:00-03:00",
      "teamA": "1º Grupo G",
      "flagA": "?",
      "abbrevA": "1G",
      "teamB": "3º colocado grupos A/E/H/I/J",
      "flagB": "?",
      "abbrevB": "3AEHIJ",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 83,
      "stage": "16 avos de final",
      "stadium": "BMO Field - Toronto, Canadá",
      "date": "2026-07-02T20:00:00-03:00",
      "teamA": "2º Grupo K",
      "flagA": "?",
      "abbrevA": "2K",
      "teamB": "2º Grupo L",
      "flagB": "?",
      "abbrevB": "2L",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 84,
      "stage": "16 avos de final",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-07-02T16:00:00-03:00",
      "teamA": "1º Grupo H",
      "flagA": "?",
      "abbrevA": "1H",
      "teamB": "2º Grupo J",
      "flagB": "?",
      "abbrevB": "2J",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 85,
      "stage": "16 avos de final",
      "stadium": "BC Place - Vancouver, Canadá",
      "date": "2026-07-03T00:00:00-03:00",
      "teamA": "1º Grupo B",
      "flagA": "?",
      "abbrevA": "1B",
      "teamB": "3º colocado grupos E/F/G/I/J",
      "flagB": "?",
      "abbrevB": "3EFGIJ",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 86,
      "stage": "16 avos de final",
      "stadium": "Hard Rock Stadium - Miami, EUA",
      "date": "2026-07-03T19:00:00-03:00",
      "teamA": "1º Grupo J",
      "flagA": "?",
      "abbrevA": "1J",
      "teamB": "2º Grupo H",
      "flagB": "?",
      "abbrevB": "2H",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 87,
      "stage": "16 avos de final",
      "stadium": "Arrowhead Stadium - Kansas City, EUA",
      "date": "2026-07-03T22:30:00-03:00",
      "teamA": "1º Grupo K",
      "flagA": "?",
      "abbrevA": "1K",
      "teamB": "3º colocado grupos D/E/I/J/L",
      "flagB": "?",
      "abbrevB": "3DEIJL",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 88,
      "stage": "16 avos de final",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-07-03T15:00:00-03:00",
      "teamA": "2º Grupo D",
      "flagA": "?",
      "abbrevA": "2D",
      "teamB": "2º Grupo G",
      "flagB": "?",
      "abbrevB": "2G",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 89,
      "stage": "Oitavas de final",
      "stadium": "Lincoln Financial Field - Philadelphia, EUA",
      "date": "2026-07-04T18:00:00-03:00",
      "teamA": "Vencedor Jogo 74",
      "flagA": "?",
      "abbrevA": "W74",
      "teamB": "Vencedor Jogo 77",
      "flagB": "?",
      "abbrevB": "W77",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 90,
      "stage": "Oitavas de final",
      "stadium": "NRG Stadium - Houston, EUA",
      "date": "2026-07-04T14:00:00-03:00",
      "teamA": "Vencedor Jogo 73",
      "flagA": "?",
      "abbrevA": "W73",
      "teamB": "Vencedor Jogo 75",
      "flagB": "?",
      "abbrevB": "W75",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 91,
      "stage": "Oitavas de final",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-07-05T17:00:00-03:00",
      "teamA": "Vencedor Jogo 76",
      "flagA": "?",
      "abbrevA": "W76",
      "teamB": "Vencedor Jogo 78",
      "flagB": "?",
      "abbrevB": "W78",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 92,
      "stage": "Oitavas de final",
      "stadium": "Estadio Azteca - Cidade do México, México",
      "date": "2026-07-05T21:00:00-03:00",
      "teamA": "Vencedor Jogo 79",
      "flagA": "?",
      "abbrevA": "W79",
      "teamB": "Vencedor Jogo 80",
      "flagB": "?",
      "abbrevB": "W80",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 93,
      "stage": "Oitavas de final",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-07-06T16:00:00-03:00",
      "teamA": "Vencedor Jogo 83",
      "flagA": "?",
      "abbrevA": "W83",
      "teamB": "Vencedor Jogo 84",
      "flagB": "?",
      "abbrevB": "W84",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 94,
      "stage": "Oitavas de final",
      "stadium": "Lumen Field - Seattle, EUA",
      "date": "2026-07-06T21:00:00-03:00",
      "teamA": "Vencedor Jogo 81",
      "flagA": "?",
      "abbrevA": "W81",
      "teamB": "Vencedor Jogo 82",
      "flagB": "?",
      "abbrevB": "W82",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 95,
      "stage": "Oitavas de final",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-07-07T13:00:00-03:00",
      "teamA": "Vencedor Jogo 86",
      "flagA": "?",
      "abbrevA": "W86",
      "teamB": "Vencedor Jogo 88",
      "flagB": "?",
      "abbrevB": "W88",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 96,
      "stage": "Oitavas de final",
      "stadium": "BC Place - Vancouver, Canadá",
      "date": "2026-07-07T17:00:00-03:00",
      "teamA": "Vencedor Jogo 85",
      "flagA": "?",
      "abbrevA": "W85",
      "teamB": "Vencedor Jogo 87",
      "flagB": "?",
      "abbrevB": "W87",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 97,
      "stage": "Quartas de final",
      "stadium": "Gillette Stadium - Boston, EUA",
      "date": "2026-07-09T17:00:00-03:00",
      "teamA": "Vencedor Jogo 89",
      "flagA": "?",
      "abbrevA": "W89",
      "teamB": "Vencedor Jogo 90",
      "flagB": "?",
      "abbrevB": "W90",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 98,
      "stage": "Quartas de final",
      "stadium": "SoFi Stadium - Los Angeles, EUA",
      "date": "2026-07-10T16:00:00-03:00",
      "teamA": "Vencedor Jogo 93",
      "flagA": "?",
      "abbrevA": "W93",
      "teamB": "Vencedor Jogo 94",
      "flagB": "?",
      "abbrevB": "W94",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 99,
      "stage": "Quartas de final",
      "stadium": "Hard Rock Stadium - Miami, EUA",
      "date": "2026-07-11T18:00:00-03:00",
      "teamA": "Vencedor Jogo 91",
      "flagA": "?",
      "abbrevA": "W91",
      "teamB": "Vencedor Jogo 92",
      "flagB": "?",
      "abbrevB": "W92",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 100,
      "stage": "Quartas de final",
      "stadium": "Arrowhead Stadium - Kansas City, EUA",
      "date": "2026-07-11T22:00:00-03:00",
      "teamA": "Vencedor Jogo 95",
      "flagA": "?",
      "abbrevA": "W95",
      "teamB": "Vencedor Jogo 96",
      "flagB": "?",
      "abbrevB": "W96",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 101,
      "stage": "Semi-final",
      "stadium": "AT&T Stadium - Dallas, EUA",
      "date": "2026-07-14T16:00:00-03:00",
      "teamA": "Vencedor Jogo 97",
      "flagA": "?",
      "abbrevA": "W97",
      "teamB": "Vencedor Jogo 98",
      "flagB": "?",
      "abbrevB": "W98",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 102,
      "stage": "Semi-final",
      "stadium": "Mercedes-Benz Stadium - Atlanta, EUA",
      "date": "2026-07-15T16:00:00-03:00",
      "teamA": "Vencedor Jogo 99",
      "flagA": "?",
      "abbrevA": "W99",
      "teamB": "Vencedor Jogo 100",
      "flagB": "?",
      "abbrevB": "W100",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 103,
      "stage": "Disputa de 3º lugar",
      "stadium": "Hard Rock Stadium - Miami, EUA",
      "date": "2026-07-18T18:00:00-03:00",
      "teamA": "Perdedor Jogo 101",
      "flagA": "?",
      "abbrevA": "RU101",
      "teamB": "Perdedor Jogo 102",
      "flagB": "?",
      "abbrevB": "RU102",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    },
    {
      "id": 104,
      "stage": "Final",
      "stadium": "MetLife Stadium - New York/New Jersey, EUA",
      "date": "2026-07-19T16:00:00-03:00",
      "teamA": "Vencedor Jogo 101",
      "flagA": "?",
      "abbrevA": "W101",
      "teamB": "Vencedor Jogo 102",
      "flagB": "?",
      "abbrevB": "W102",
      "goalsA": null,
      "goalsB": null,
      "status": "scheduled"
    }
  ];



  for (const km of allMatches) {
    await prisma.game.create({
      data: {
        stadium: km.stadium,
        stage: km.stage,
        date: km.date,
        teamA: km.teamA,
        teamB: km.teamB,
        flagA: km.flagA,
        flagB: km.flagB,
        abbrevA: km.abbrevA,
        abbrevB: km.abbrevB,
        status: 'scheduled'
      }
    });
  }

  console.log('Semeados 6 jogos de mata-mata.');
  console.log('Seeding concluído com sucesso!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
